server:
  port: 9898
spring:  
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.UQwqTNtxjnUGzIfHYti3nZxs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security
    username: ${IDENTITY.datasource.username}
    password: ${IDENTITY.datasource.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect :org.hibernate.dialect.MySQL8Dialect    
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, env
  endpoint:
    env:
      enabled: true      
